services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8003:8003"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8004:8004"
    environment:
      BACKEND_URL: http://backend:8003
    depends_on:
      - backend
