services:
  backend:
    build: ./backend
    ports:
      - "8003:8003"

  frontend:
    build: ./frontend
    ports:
      - "8004:8004"
    environment:
      BACKEND_URL: http://backend:8003
    depends_on:
      - backend
